project:
  type: website

website:
  title: 'Critical AI Literacy for Historians'
  favicon: favicon.png
  open-graph: true
  twitter-card: true
  site-url: https://maehr.github.io/critical-ai-literacy-for-historians/
  repo-url: https://github.com/maehr/critical-ai-literacy-for-historians/
  issue-url: https://github.com/maehr/critical-ai-literacy-for-historians/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: favicon.svg
    logo-alt: 'Critical AI Literacy for Historians'
    title: 'Critical AI Literacy'
    tools:
      - icon: github
        url: https://github.com/maehr/critical-ai-literacy-for-historians/
    left:
      - text: English
        href: en/index.qmd
      - text: Deutsch
        href: de/index.qmd
      - text: Français
        href: fr/index.qmd
      - text: ℹ️
        menu:
          - text: About (EN)
            href: en/about.qmd
          - text: Über das Projekt (DE)
            href: de/about.qmd
          - text: À propos (FR)
            href: fr/about.qmd
  sidebar:
    - id: en
      title: 'English'
      style: 'floating'
      collapse-level: 2
      contents:
        - text: 'Home'
          href: en/index.qmd
        - section: 'Exercises'
          href: en/exercises/index.qmd
          contents: en/exercises/*
        - text: About
          href: en/about.qmd
        - text: Bibliography
          href: en/bibliography.qmd
    - id: de
      title: 'Deutsch'
      style: 'floating'
      collapse-level: 2
      contents:
        - text: 'Startseite'
          href: de/index.qmd
        - text: 'Übungen'
          href: de/exercises/index.qmd
          contents: de/exercises/*
        - text: Über das Projekt
          href: de/about.qmd
        - text: Bibliographie
          href: de/bibliography.qmd
    - id: fr
      title: 'Français'
      style: 'floating'
      collapse-level: 2
      contents:
        - text: 'Accueil'
          href: fr/index.qmd
        - section: 'Exercices'
          href: fr/exercises/index.qmd
          contents: fr/exercises/*
        - text: À propos
          href: fr/about.qmd
        - text: Bibliographie
          href: fr/bibliography.qmd
format:
  html:
    toc: true
    theme:
      - brand
      - cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    canonical-url: true

freeze: true

editor: visual
