contact_links:
  - name: Are you looking for documentation on Critical AI Literacy for Historians?
    url: https://maehr.github.io/critical-ai-literacy-for-historians
    about: Please see the documentation for Critical AI Literacy for Historians on its GitHub Pages page.
  - name: Do you want to discuss Critical AI Literacy for Historians with the community?
    url: https://github.com/maehr/critical-ai-literacy-for-historians/discussions
    about: Please see the discussions page for Critical AI Literacy for Historians.
blank_issues_enabled: true
